name: CI/CD Frontend

on:
  push:
    branches:
      - main

jobs:
  ubuntu-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

  publish-artifact:
    needs: ubuntu-build
    runs-on: ubuntu-latest
    steps:
    - name: Archive production-ready files
      uses: actions/upload-artifact@v2
      with:
        name: published-app
        path: dist/FrontendProject