name: Deploy Frontend

on:
  workflow_run:
    workflows: ["CI/CD Frontend"]
    types:
      - completed
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:
      ENVIRONMENT: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Netlify
        if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.name == 'CI/CD Frontend' && github.event_name == 'push'
        env:
          NETLIFY_SITE_NAME: ${{ secrets.NETLIFY_SITE_NAME }}
          NETLIFY_OWNER: ${{ secrets.NETLIFY_OWNER }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          # Install Netlify CLI
          npm install -g netlify-cli

          # Netlify deployment for Dev
          if [ "$ENVIRONMENT" == "dev" ]; then
            echo "Deploying to $ENVIRONMENT environment"
            netlify login --auth $NETLIFY_AUTH_TOKEN
            netlify deploy -e dev
          fi

          # Manual deployment for Staging
          if [ "$ENVIRONMENT" == "staging" ]; then
            echo "Manual deployment to Staging environment. Run the following command locally:"
            echo "netlify login --auth $NETLIFY_AUTH_TOKEN && netlify deploy -e staging"
          fi

          # Manual deployment for Prod
          if [ "$ENVIRONMENT" == "prod" ]; then
            echo "Manual deployment to Prod environment. Run the following command locally:"
            echo "netlify login --auth $NETLIFY_AUTH_TOKEN && netlify deploy -e prod"
          fi