name: Deploy Frontend

on:
  workflow_run:
    workflows: ["CI/CD Frontend"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
          matrix:
            node-version: [18.x]

    env:
      # Set the environment variable to 'dev', 'staging', or 'prod' based on your needs
      ENVIRONMENT: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Netlify
        if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.name == 'CI/CD Frontend'
        env:
          NETLIFY_SITE_NAME: ${{ secrets.NETLIFY_SITE_NAME }}
          NETLIFY_OWNER: ${{ secrets.NETLIFY_OWNER }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          # Install Netlify CLI
          npm install -g netlify-cli

          # Netlify deployment for Dev
          if [ "$ENVIRONMENT" == "dev" ]; then
            echo "Deploying to $ENVIRONMENT environment"
            netlify login
            netlify deploy
          fi

          # Netlify deployment for Staging
          if [ "$ENVIRONMENT" == "staging" ]; then
            echo "Deploying to Staging environment"
            netlify login
            netlify deploy
            # Additional staging deployment steps can be added here
          fi

          # Netlify deployment for Prod
          if [ "$ENVIRONMENT" == "prod" ]; then
            echo "Deploying to Prod environment"
            netlify login
            netlify deploy
            # Additional prod deployment steps can be added here
          fi

sso:
  entityID: https://api.netlify.com/saml/my-team
  loginURL: https://api.netlify.com/saml/my-team/init
  acsURL: https://api.netlify.com/saml/my-team/acs
