name: Netlify Prod Deploy

on:
  push:
    branches:
      - prod

jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    environment: PROD
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Dependencies
      run: npm install

    - name: Build for prod
      run: npm run build -- --configuration=production

    - name: Deploy to prod
      env:
        NETLIFY_SITE_NAME: ${{ secrets.NETLIFY_PROD_SITE_NAME }}
        NETLIFY_OWNER: ${{ secrets.NETLIFY_OWNER }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PROD_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      run: |
        npm install -g netlify-cli
        netlify login --auth $NETLIFY_AUTH_TOKEN
        netlify deploy --prod

    - name: Configure Git
      run: |
        git config --global user.email "assamtomi@gmail.com"
        git config --global user.name "AssemToumi"

    - name: Bump Version
      run: |
        npm version patch -m "Bump version to %s [skip ci]"
        git push --follow-tags
  
    - name: Install GitHub CLI
      run: |
        sudo apt install -y software-properties-common
        sudo add-apt-repository -y https://cli.github.com/packages
        sudo apt update
        sudo apt install gh
  
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create v$(node -p "require('./package.json').version") -t "Release $(node -p "require('./package.json').version")" -n "Release $(node -p "require('./package.json').version")" dist/*
